from tgbot.misc.i18n import i18ns

_ = i18ns.lazy_gettext

textss = {"Oziq - ovqat maxsulotlari": {"Bakaleya": ["Konservalangan sabzavotlar", "Makaronlar", "Dukkakliklar",
                                                     "Konservalangan baliklar",
                                                     "Konservalangan go'sht", "Pishiriqlar va disertlar uchun tovarlar",
                                                     "Quruq nonushta (nesquik)", "Shakar ",
                                                     "Souslar (ketchup, mayonez, soya)",
                                                     "Tez tayyorlanadigan maxsulotlar (hotlunch, rollton)", "Tuz",
                                                     "Un ", "Yoglar",
                                                     "Yormalar",
                                                     "Ziravorlar va oziqaviy qo'shimchalar"],
                                        "Choy, Qahva, Issiq ichimlikalr": ["Qo'shimchalar qo'shilgan choy",
                                                                           "Donli qaxvalar",
                                                                           "Giyoxli choylar",
                                                                           "Kakao, issik shokolad",
                                                                           "Kapsulalardagi qaxvalar ", "Ko'k choy",
                                                                           "Maydalangan qaxva", "Qora choy"],
                                        "Suv, Sharbat, ichimlikalar": ["Energetik ichimliklar", "Gazlangan ichimliklar",
                                                                       "Limonadlar",
                                                                       "Kvas, yaxna choy", "Morslar, kompotlar",
                                                                       "Sharbatlar, nektarlar, smuzilar",
                                                                       "Gazli va gazsiz suvlar"],
                                        "Shokolad, konfetlar, Shirinliklar": ["Saqichlar", "Batonchalar",
                                                                              "Konfetlar, karamellar, surgichlar",
                                                                              "Pryaniklar, vaflilar",
                                                                              "Qutili konfetlar", "Shokolad, kinder",
                                                                              "Shokoladli, yong'okli pasta (nutella, chokotella)",
                                                                              "To'rtlar, ruletlar, kekslar",
                                                                              "Zefir, pastali, marmelad"],
                                        "Yong'oqlar, Quritilgan mevalar, pistalar": ["Yongoklar, quritilgan mevalar",
                                                                                     "Mevali chipslar", "Pistalar",
                                                                                     "quriq mevalar"],
                                        "Shirin konservalar": ["Asal va asalarichilik maxsulotlari",
                                                               "Konservalangan mevalar",
                                                               "Murabbo va jemlar"],
                                        "Sneklar": ["Chips", "popkorn",
                                                    "Dudlangan, koki qilingan, quritilgan maxsulotlar",
                                                    "Pechenye, kreker",
                                                    "Qarsildok nonlar", "Suxariklar, krekerlar"],
                                        "Bolalar ovqati": ["Batonchalar", "Bolalar aralashmasi", "Bolalar bo'tqasi",
                                                           "Ichimliklar", "Pechenye, kreker", "Pyure"],
                                        "Sog'lom ovqatlanish": ["Dengiz o'tlari", "O'simlik suti", "Qarsildok nonlar",
                                                                "Tez tayyorlanadigan sho'rvalar"],
                                        "Sut va sut maxsulotlari": ["Qadoqlangan sutlar", "Quyltirilgan sut (Maloko)",
                                                                    "Qatiqlar", "Smetanalar", "Kefirlar", "Yogurtlar",
                                                                    "Sariyoglar", "Margarinlar", "Pishloqlar",
                                                                    "Tvoroglar", "Plavlenniy sir (cream cheese)"],
                                        "Non va non maxsulotlari": ["Yopgan non", "Qolipli non (buxonka)", "Yogli non",
                                                                    "Patirlar", "Qora non", "Tosterlar", "Bulochkalar"],
                                        "Yarim tayyor maxsulotlar": ["Chuchvara", "Somsa xamir", "Somsa",
                                                                     "Pitsa xamiri",
                                                                     "Lagmon", "Kotlet", "Lavash xamir"]},
          "Go'zallik": {"Makiyaj": ["Ko'zlar", "Lablar", "Makiyaj uchun aksessuarlar", "Qoshlar", "Yuz"],
                        "Yuz parvarishi": ["Muammoli terilar uchun maxsulotlar", "Namlash va oziklantirish", "Niqoblar",
                                           "Patichlar", "Skrab va piling", "Tozalash va yuvish"],
                        "Soch parvarishi": ["Aksesuarlar", "Buyash va kimyoviy jingalak kilish",
                                            "Sartarosh uchun professional asboblar",
                                            "Tozalash va parvarish uchun vositalar",
                                            "Turmaklash uchun vositalar"],
                        "Tana parvarishi": ["Aksesuarlar", "Dush va vanna uchun vositalar", "Namlash va oziqlantirish",
                                            "Quyoshda toblanish va quyoshdan ximoyalash"],
                        "Manikyur va pedyikyur": ["Gel-laklar", "Laklar",
                                                  "Praymerlar va yog'larni yo'qotuvchi maxsulotlar",
                                                  "Tirnok bo'yogini tozalovchi vositalar",
                                                  "Tirnok yopishtirish uchun materyallar"],
                        "To'plam": ["Sochlar uchun kosmetika to'plamlari",
                                    "Tana parvarishi uchun kosmetika  to'plamlari",
                                    "Yuz uchun to'plamlar"],
                        "Erkaklar uchun": ["Soch uchun", "Soqol va muylovlar uchun", "Yuz tana parvarishi"],
                        "Parfyumeriya": ["Aromat yog'lar", "Atirlar", "Odekolonlar", "Parfyumlangan suv",
                                         "Qurik atirlar",
                                         "Selektiv parfyumeriya", "Xushbuylangan suv"]},
          "Maishy kimyoviy moddalar": {
              "Xavoni musaffolashtirgichlar": ["Xavo tozalovchilar", "Xidlarni neytralash vositalari",
                                               "Xushbo'ylashtirgichlar"],
              "Idish yuvish vositalari": ["Kapsulalar va chayish vositalari", "Tabletkalar"],
              "Intim gigiyena": ["Dezodarantlar va antiperspirantlar", "Intim gigiyenasi uchun vositalar",
                                 "Prokladkalar va tanponlar"],
              "Og'iz bo'shligi gigiyenasi": ["Tish cho'tkalar", "Tish pastalar va gellar",
                                           "Tish okartiruvchi vositalar"],
              "Poyabzallarni parvarish kilish vositalari": ["Dezodarantlar", "Kremlar va vosklar",
                                                            "Poyabzal uchun buyoqlar",
                                                            "Poyabzal uchun chutkalar va gupkalar"],
              "Qogoz va paxta maxsulotlari": ["Nam salfetkalar", "Paxta yostiqchalari", "Paxta tayoqchalari",
                                              "Qogoz sochiklar va salfetkalar", "Xojatxona qogozi"],
              "Soqol olish uchun tovarlar": ["Britvalar, uskunalar", "Gellar va kupiklar",
                                             "Sokkol olish uchun tuplamlar va aksuarlar",
                                             "Sokol olishdan oldingi va keyingi surtiladigan vositalar"],
              "Sovun va xujalik sovuni": ["Beldilar", "Kosmetik sovun", "Xujalik sovunlari",
                                          "Skrab, suvenir, suyuk, yuvunish sovunlari"],
              "Maishiy texnika parvarishi uchun vositalar": ["Idish yuvish mashinalari uchun",
                                                             "Kir yuvish mashinalari uchun",
                                                             "Choynaklar uchun",
                                                             "Suvni yumshatish vositalari"],
              "Yuvish uchun vositalar": [
                  "Idish yuvish vositalari", "Mebel va polni parvarishlash uchun vositalar",
                  "Universal tozalash vositasi", "Vanna va xojatxona uchun vositalar",
              ],
              "Tozalash va yuvish vositalari": [
                  "Gel va suyukliklar", "Kapsulalar va tabletkalar", "Kir yuvish kukuni",
                  "Konditsionerlar va chayish vositalari", "Okartirgichlar va dog ketkazgichlar"]
          },
          "Hayvonlar uchun maxsulotlar": {
              "Gigiena": ["Gigiyena vositalari", "Xayvonlar uchun kosmetika", "Xayvonlarni parvarish kilish vositalari",
                          "Plyonkalar va tagliklar", "Spreylar va xidni yuk kilish vositalari"],
              "Itlar uchun": ["Itlar uchun buyinbog", "Itlar uchun xojatxonalar", "Itlar uchun kiyim va poyabzal",
                              "Ovqat beradigan idishlar", "Ozuqa va shirinliklar", "Uyinchoklar"],
              "Mushuklar uchun": ["Mushuklar uchun xojatxonalar", "Mushuklar uchun kiyim va tushaklar",
                                  "Ovqat beradigan idishlar", "Ozuqa va shirinliklar", "Uyinchoqlar"]}}

mahalla_dict = {
    "Shahrisabz t": ["Duxchi MFY", "Yangibog MFY", "Miraki MFY", "Xisor MFY", "Abziyot MFY", "Bogishamol MFY",
                     "Avazmalik MFY", "Shanbe MFY", "Kurgontepa MFY", "Bigmi MFY", "Paxtakor MFY", "Kiyomshayx MFY",
                     "Xalkabod MFY", "Chorbog MFY", "Saroy MFY", "Tanxoz MFY", "Urtakurgon MFY", "Kumkishlok MFY",
                     "Navbaxor MFY", "Shamaton MFY", "Istikbol MFY", "Xujaxuroson MFY", "Xontepa MFY",
                     "Yangikishlok MFY", "Xojimaydon MFY", "Nurafshon MFY", "Yangiobod MFY", "Maktaobod MFY",
                     "Tepar MFY", "Ok-oltin MFY", "Kushkanot MFY", "Tudamaydon MFY", "Ravot MFY", "Sayyod MFY",
                     "Xisorak MFY", "Xazara MFY", "Chorshanbe MFY", "Temirchi MFY", "Obod MFY", "Gelon MFY",
                     "Sarchashma MFY", "Kushchinor MFY",
                     "Аmir Temur MFY", "Uloch MFY", "Shiromon MFY", "Kul MFY", "Toshbulok MFY", "Okdaryo MFY",
                     "Polmon MFY", "Xitoy MFY", "Olmazor MFY", "Mevazor MFY", "Аchchigi MFY", "Shakarteri MFY",
                     "Loliston MFY", "Kutchi MFY", "Chukun MFY"],
    "Shahrisabz sh": ["Zargarlik MFY", "Ipak Yuli MFY", "Dustlik MFY", "Maьrifat MFY", "Namaton MFY", "Guliston MFY",
                      "Qorasuv MFY", "Fayzobod MFY", "Xujamurod Baxshi MFY", "Gʼalaba MFY", "Ziyokor MFY",
                      "Navroʼz MFY", "Nomozgox MFY", "Oʼrda MFY", "Qoziguzar MFY",
                      "Qushxona MFY", "Kulollik MFY", "Uychilik MFY", "Kunchikar MFY", "Qoʼshxovuz MFY", "Teparlik MFY",
                      "Аmmogʼon MFY", "Tutzor MFY", "Choshtepa MFY", "Oq saroy MFY", "Bogibaxor MFY",
                      "Yashil Diyor MFY",
                      "Uymavut MFY", "Turon MFY", "Sinabogʼ MFY", "Kamolot MFY", "Pillakashlik MFY", "Sariosiyo MFY",
                      "Katta Novkat MFY", "Yagnixayot MFY",
                      "Boʼston MFY", "Xabarlik MFY", "Kesh MFY", "Bunyodkor MFY", "Zingiron MFY"],
    "Qarshi t": ["Shoyxuja MFY", "Gubdin MFY", "Tinchlik MFY", "Uzumzor MFY", "Guliston MFY", "Kuchkak MFY",
                 "Bogobod KFY", "Chaman MFY",
                 "Kirayit MFY", "Xilol MFY", "Parvoz MFY", "Xonobod MFY", "YaNGI XONOBOD MFY", "YaNGI BOGOBOD MFY",
                 "Taxtapul MFY", "Kat MFY", "Paxtazor MFY", "Mangit MFY", "Chulibuston KFY", "Koratepa MFY",
                 "Istiklol MFY", "Fayzobod MFY", "Saroy MFY", "Mustakillik MFY", "Jumabozor MFY", "Xonyon MFY",
                 "Dasht MFY", "Tarakkiyot MFY", "Charagil kishlogi", "YaNGI BАTOSh MFY", "Mirmiron MFY",
                 "Mevazor MFY", "GULShАN MFY", "Erteap MFY", "Tallikuron MFY", "Nukrabod MFY", "Batosh MFY",
                 "Shodlik MFY",
                 "Poshton KFY", "Paxtakor MFY", "Kuyibeshkent MFY", "Bodomzor MFY", "Navbaxor MFY", "Navoiy MFY",
                 "Navruz MFY",
                 "Bunyodkor MFY", "Dustlik MFY", "Rovot MFY", "Potron MFY", "Omontepa MFY", "Yangixayot MFY",
                 "Kovchin MFY", "Sherkent MFY", "Kaxlak MFY", "Kojor MFY", "Korakuchchi MFY", "Lagandi MFY",
                 "Uzbekiston mustakilligi MFY"],
    "Qarshi sh": ["Ravok MFY", "Kunchikar MFY", "Xontepa MFY", "Bogishamol MFY", "Xuja-Xiyol MFY", "Nasaf MFY",
                  "Аral MfY", "Neftchi MFY", "Paxtazor-1 MFY", "Tabassum MFY",
                  "А.Temur MFY", "Xaramjuy MFY", "Charmgar MFY", "Maxsumobod MFY", "Аralovul MFY", "Karshi MFY",
                  "Temir Yulchi MFY", "Buyuk Turon MFY", "Shoxbekat MFY", "G.Gulom MFY", "Xudoyzot MFY",
                  "Oktepa (F.Xujaev) MFY", "Kat MFY", "Gungon MFY", "Oydin MFY", "Yangi Turmush MFY", "Nuriston MFY",
                  "Karluk Bogot MFY", "Navo m", "Kaxshab MFY",
                  "Navoiy MFY", "Mustakillik MFY", "Kavali MFY", "Istiklol MFY", "Chulkuvar MFY", "Shodlik MFY",
                  "Karlikxona MFY", "Paxtazor MFY", "Komilon MFY", "Maxallot MFY", "Buston MFY",
                  "Kilichbek Kurgoncha MFY", "Magzon MFY",
                  "Kamandi MFY", "GULShАN MFY", "Samarkand MFY", "Darvoza-Tutak MFY", "Beglar MFY", "Kurgoncha MFY",
                  "Navruz MFY", "Roguzar MFY", "Chakar MFY", "Eski anxor MFY", "Geolog MFY", "Zogza MFY",
                  "Zaxoki-Maron MFY", "Shurtan MFY", "Batosh MFY", "Shayxali MFY", "Аrabxona MFY",
                  "Shayxali shaxarchasi MFY", "Otchopar MFY", "Bunyodkor MFY"],
    "Qamashi": ["Kovchin MFY", "Kuyi Yangi MFY", "Kizilkishlok MFY", "Dovut MFY", "Bogobod MFY", "Koratepa MFY",
                "Аzlartepa MFY", "Mayda MFY", "Korabog MFY", "Kungirot MFY", "Boburtepa MFY", "Berdoli MFY",
                "Boyburi MFY", "Chim MFY", "Gulshan MFY", "Kaptarxona MFY", "Mexir MFY", "Jonbuzsoy MFY",
                "Uzbekiston MFY", "Obod MFY", "Ulugbek MFY", "Zafar MFY", "Dustlik MFY", "Samarkand MFY",
                "Loykasoy MFY", "Bunyodkor MFY", "Kiziltepa MFY", "Elobod MFY", "Changak MFY", "Chukurkishlok MFY",
                "Urtadara MFY", "Kukbulok MFY", "Odokjonbuz MFY", "Paxtaobod MFY",
                "Istikbol MFY", "Kishlik MFY", "Kattaura MFY", "Korasuv MFY", "Ibn-Sino MFY", "Mangit MFY",
                "Navoiy MFY", "Jonbuz MFY", "Kushkapa MFY", "Sarbozor MFY", "Soxibkor MFY", "Gishli MFY", "Okrabod MFY",
                "Rabod MFY", "Uzun MFY", "Yuksalish MFY", "Oynakul MFY", "Savsantepa MFY", "Tukboy MFY", "Yortepa MFY",
                "Okguzar MFY", "Olmazor MFY", "Kamay MFY", "Badaxshon MFY", "Nurli yul MFY", "Balandchayyla MFY"],
    "Koson": ["Mulali MFY", "Nartibaland MFY", "Dustlik MFY", "Mudin MFY", "Аyronchi MFY", "Maydayobu MFY",
              "Shirinobod FUUBO MFY", "Navnixol FUUBO MFY", "Yukori Mudin MFY", "Yukori Аrabxona FUUBO MFY",
              "Pistali MFY", "Darcha MFY", "Mustakillik MFY", "Beshkutan MFY", "Farovan MFY", "Korabayr MFY",
              "Nixol MFY", "Esaboy MFY", "Xalima MFY", "Toshkuprik MFY", "Zamin FUUBO Boygundi MFY", "Sherbek MFY",
              "Pudina MFY", "Yukori Obron MFY", "Regzor MFY", "Аralik MFY", "Ravot MFY", "Saripul MFY", "Lolazor MFY",
              "Navbaxor MFY", "Paxtaxor MFY", "Kazokli MFY", "Nekuz FUUBO Boyterak MFY", "Kungirtog FUUBO Gala MFY",
              "Yuksalish FUUBO Ushoktepa MFY", "Bunedkor MFY", "Etak MFY", "Istiklol FUUBO Nurafshon MFY",
              "Gulobod FUUBO Navruz MFY", "Koson FUUBO MFY", "Tarakkiyot FUUBO Guliston MFY", "Xujakuduk MFY",
              "Raimsufi MFY", "Uyrot MFY", "Yakkasaroy MFY", "Birdamlik FUUBO", "Yuqori Maydayobu MSG",
              "Tinchlik FUUBO",
              "Surxon MFY", "Chirokchi MFY", "Obod MFY", "Shirintepa MFY", "Xalkobod MFY", "Gulbog MFY", "Аrabxona MFY",
              "Kuybog MFY", "Bogishamol FUUBO", "Istikbol MFY", "Jizzalik MFY", "Yangiobod MFY", "Mugjagul MFY",
              "Nartichukur MFY", "Mesit MFY", "Mashʼal MFY", "Urta Obron MFY", "Kuyi Obron MFY", "Chorbog FUUBO",
              "Аlachabob MFY"],
    "Muborak": ["Muborak MFY", "Sardoba MFY", "Karlik MFY", "Buston MFY", "Yangiobod MFY",
                "Paxtakor MFY", "Barkamol avlod MFY", "Xitoy MFY", "Yashnaobod MFY",
                "Obod turmush MFY",
                "Korakum MFY", "А.Temur MFY", "Sarik MFY", "Kuxnashaxar MFY", "Mashʼal MFY",
                "А.Navoiy MFY", "Geolog MFY", "Uzbekiston MFY", "Konchilar MFY", "Yoshlik MFY",
                "Tong MFY", "Dustlik MFY",
                "Bobur MFY", "Kuruvchilar MFY", "Istiklol MFY"],
    "Nishon": ["Paxtaobod MFY", "Paxtazor MFY", "Paxtakor MFY", "Baynalminal MFY", "Ulugbek MFY", "Navbaxor MFY",
               "Yuksalish MFY", "Yoshlar Diyori MFY", "Ibn-Sino MFY", "Oydin MFY",
               "Ok-oltin MFY", "Katta Аnxor MFY", "А.Kodiriy MFY", "Shirinobod MFY", "Yangiobod MFY", "Obod MFY",
               "Obi-xayot MFY", "Tinchlik MFY", "Dustlik MFY", "Kuksoy MFY", "Guliston MFY", "Istikbol MFY",
               "Kirkkuloch MFY", "Kimyogar MFY", "Jalajin MFY", "Gulzor MFY", "Orzu Bustoni MFY", "Balxiyak MFY",
               "Samarkand MFY", "Janub mashaʼli MFY", "Kaptarli MFY", "Umr Bunyodkori MFY", "Navruz MFY", "Nurchi MFY",
               "Nuriston MFY", "Nishon MFY"],
    "Chiroqchi": ["Paxtaobod MFY", "Paxtazor MFY", "Paxtakor MFY", "Baynalminal MFY", "Ulugbek MFY", "Navbaxor MFY",
                  "Yuksalish MFY", "Yoshlar Diyori MFY", "Ibn-Sino MFY", "Oydin MFY",
                  "Ok-oltin MFY", "Katta Аnxor MFY", "А.Kodiriy MFY", "Shirinobod MFY", "Yangiobod MFY", "Obod MFY",
                  "Obi-xayot MFY", "Tinchlik MFY", "Dustlik MFY", "Kuksoy MFY", "Guliston MFY", "Istikbol MFY",
                  "Kirkkuloch MFY", "Kimyogar MFY", "Jalajin MFY", "Gulzor MFY", "Orzu Bustoni MFY", "Balxiyak MFY",
                  "Samarkand MFY", "Janub mashaʼli MFY", "Kaptarli MFY", "Umr Bunyodkori MFY", "Navruz MFY",
                  "Nurchi MFY",
                  "Nuriston MFY", "Nishon MFY"],
    "Yakkabog'": ["Shodlik MFY", "Darxon MFY", "Kayrogoch MFY", "Daryo MFY", "Kushtegirmon MFY", "Sovukbulok MFY",
                  "Sandal MFY",
                  "Farovonlik MFY", "Ulamji MFY", "Yashnobod MFY", "Madaniyat MFY", "Gozlik MFY", "Choydori MFY",
                  "Jiyda MFY", "Uzun MFY",
                  "Kushchinor MFY", "Mevazor MFY", "Аlakuylak MFY", "Istiqbol MFY", "Kishlik MFY", "Xiyobon MFY",
                  "Katogon MFY", "Uchtepa MFY",
                  "Istiklol MFY", "Chinobod MFY", "Doʼstlik MFY", "Shirozi MFY", "Beshugil MFY", "Kattabog MFY",
                  "Koratut MFY", "Uygur MFY",
                  "Navruz MFY", "Esat MFY", "Yangixayot MFY", "Tukboy MFY", "Paxtakor MFY", "Nurli yoʼl MFY",
                  "Xonaka MFY", "Turon MFY", "Samok MFY",
                  "Serob MFY", "Tatar MFY", "Urta MFY", "Ishkent MFY", "Guliston MFY", "Eski Yakkabog ShFY",
                  "Sharsharbogot MFY", "Ibn Sino MFY", "Mustakillik MFY",
                  "Yoshlik MFY", "Oktosh MFY", "Аygirkul MFY", "Jaychi MFY", "Nurafshon MFY", "Xujailgor MFY",
                  "Yangiobod MFY", "Chumich MFY",
                  "Jambul MFY", "Kenguzar MFY", "Bunyodkor MFY", "Obod MFY", "Tollibulok MFY"],
    "Kitob": ["Buston MFY", "Yangi Zamon MFY", "Navruz MFY", "Navbaxor MFY", "Shurobsoy MFY", "Soxibkor MFY",
              "Ulugʼbek MFY", "Xalqlar Doʼstligi MFY", "Xoji MFY",
              "Istiqbol MFY", "Jilisuv MFY", "Bektemir MFY", "Аlaquyliq MFY", "Bogʼbon MFY", "Guliston MFY",
              "Kuxsor MFY", "Bashir MFY",
              "Saroy MFY", "Iskana MFY", "Tupchoq MFY", "Palandara MFY", "Obikanda MFY", "Katlos MFY", "Tuyaboshi MFY",
              "Аli-Qushchi MFY",
              "Yangiobod MFY" "Varganza MFY", "Bogʼi-Baland MFY", "Makrid MFY", "Qaynar MFY", "Sanam MFY",
              "Mustaqillik MFY", "Charimgar MFY",
              "Sharq Yulduzi MFY", "Samarkand MFY", "Oyoqchi MFY", "Qashqadaryo MFY", "Zarafshon MFY", "Baxor MFY",
              "Yakkatut MFY", "Paxtaobod MFY",
              "Denov MFY", "Beshqazoq MFY", "Obod MFY", "Sevaz MFY", "Surum MFY", "Xamid Olimjon MFY", "Parchakent MFY",
              "Beshterak MFY",
              "Birlik MFY", "Qorabuloq MFY", "Qushdaryo MFY", "Nurafshon MFY", "Panji MFY", "Oq-suv MFY",
              "Sariosiyo MFY", "Xujailmkoni MFY", "Toshkent MFY", "Аnorzor MFY"],
    "Kasbi": ["Chulkuvar KFY", "Nazartepa MFY", "Paxtakor MFY", "Jarkucha MFY", "Denov MFY", "Kamashi MFY",
              "Xujaki MFY", "Mushkkoki MFY",
              "Mustakilobod MFY", "Bogarik MFY", "Oktepa MFY", "Talliyulgun MFY", "Fazli MFY", "Pandiron MFY",
              "Gʼalaba MFY", "Karatepa MFY",
              "Doʼstlik MFY", "Muglon MFY", "Xuja-kasbi MFY", "Okkamish MFY", "Tinchlik MFY", "Shakarjuy MFY",
              "Jizza MFY", "Yuksalish MFY",
              "Xuja-xayron MFY", "Obod yurt MFY", "Komilon MFY", "Kungirot MFY", "Korakungirot MFY", "M.Ulugbek MFY",
              "Mesit MFY", "Okjangal MFY",
              "Katagan MFY", "Maymanok MFY", "Soxibkor MFY", "Istiklol MFY", "Nurobod MFY", "Obod Nekuz MFY",
              "Talishbe MFY", "Kasbi MFY", "Xujakarlik MFY"],
    "Guzor": ["Jararik MFY", "Yonkishlok MFY", "Gulshan MFY", "Eskibog MFY", "Xalkobod MFY", "Yangiobod MFY",
              "Yangikent MFY",
              "Shakarbulok MFY", "Korakul MFY", "Eshonkuduk MFY", "Sherali MFY", "Sovligar MFY", "Kovchin MFY",
              "Zarbdor MFY",
              "Chorvador MFY", "Dultali MFY", "Guliston MFY", "Toshguzar MFY", "Buston MFY", "Istikbol MFY",
              "Mevazor MFY",
              "Fayzobod MFY", "Yangi xayot MFY", "Dashtobod MFY", "Obi xayot MFY", "Omonota MFY", "Pachkamar MFY",
              "Mustakillik MFY",
              "Paxtazor MFY", "Аmir Temur MFY", "Tinchlik MFY", "Obod MFY", "Xujaguzar MFY", "Chanok MFY",
              "Muminobod MFY", "Batosh MFY",
              "Xumdon MFY", "Аvgonbog MFY", "Chakar MFY", "Yakkadaraxt MFY", "Chugurtma MFY", "Kushtepa MFY",
              "Tengdosh MFY", "Chumichli MFY",
              "Mexnatobod MFY", "Savbog MFY", "Yargunchi MFY", "Аpardi MFY", "Dustlik MFY", "Buyuk karvon yuli MFY",
              "Navruz MFY"],
}
