from tgbot.misc.i18n import i18ns

_ = i18ns.lazy_gettext

textss = {"Oziq - ovqat maxsulotlari": {"Bakaleya": ["Konservalangan sabzavotlar", "Makaronlar", "Dukkakliklar",
                                                     "Konservalangan baliklar",
                                                     "Konservalangan go'sht", "Pishiriqlar va disertlar uchun tovarlar",
                                                     "Quruq nonushta (nesquik)", "Shakar ",
                                                     "Souslar (ketchup, mayonez, soya)",
                                                     "Tez tayyorlanadigan maxsulotlar (hotlunch, rollton)", "Tuz",
                                                     "Un ", "Yoglar",
                                                     "Yormalar",
                                                     "Ziravorlar va oziqaviy qo'shimchalar"],
                                        "Choy, Qahva, Issiq ichimlikalr": ["Qo'shimchalar qo'shilgan choy",
                                                                           "Donli qaxvalar",
                                                                           "Giyoxli choylar",
                                                                           "Kakao, issik shokolad",
                                                                           "Kapsulalardagi qaxvalar ", "Ko'k choy",
                                                                           "Maydalangan qaxva", "Qora choy"],
                                        "Suv, Sharbat, ichimlikalar": ["Energetik ichimliklar", "Gazlangan ichimliklar",
                                                                       "Limonadlar",
                                                                       "Kvas, yaxna choy", "Morslar, kompotlar",
                                                                       "Sharbatlar, nektarlar, smuzilar",
                                                                       "Gazli va gazsiz suvlar"],
                                        "Shokolad, konfetlar, Shirinliklar": ["Saqichlar", "Batonchalar",
                                                                              "Konfetlar, karamellar, surgichlar",
                                                                              "Pryaniklar, vaflilar",
                                                                              "Qutili konfetlar", "Shokolad, kinder",
                                                                              "Shokoladli, yong'okli pasta (nutella, chokotella)",
                                                                              "To'rtlar, ruletlar, kekslar",
                                                                              "Zefir, pastali, marmelad"],
                                        "Yong'oqlar, Quritilgan mevalar, pistalar": ["Yongoklar, quritilgan mevalar",
                                                                                     "Mevali chipslar", "Pistalar",
                                                                                     "quriq mevalar"],
                                        "Shirin konservalar": ["Asal va asalarichilik maxsulotlari",
                                                               "Konservalangan mevalar",
                                                               "Murabbo va jemlar"],
                                        "Sneklar": ["Chips", "popkorn",
                                                    "Dudlangan, koki qilingan, quritilgan maxsulotlar",
                                                    "Pechenye, kreker",
                                                    "Qarsildok nonlar", "Suxariklar, krekerlar"],
                                        "Bolalar ovqati": ["Batonchalar", "Bolalar aralashmasi", "Bolalar bo'tqasi",
                                                           "Ichimliklar", "Pechenye, kreker", "Pyure"],
                                        "Sog'lom ovqatlanish": ["Dengiz o'tlari", "O'simlik suti", "Qarsildok nonlar",
                                                                "Tez tayyorlanadigan sho'rvalar"],
                                        "Sut va sut maxsulotlari": ["Qadoqlangan sutlar", "Quyltirilgan sut (Maloko)",
                                                                    "Qatiqlar", "Smetanalar", "Kefirlar", "Yogurtlar",
                                                                    "Sariyoglar", "Margarinlar", "Pishloqlar",
                                                                    "Tvoroglar", "Plavlenniy sir (cream cheese)"],
                                        "Non va non maxsulotlari": ["Yopgan non", "Qolipli non (buxonka)", "Yogli non",
                                                                    "Patirlar", "Qora non", "Tosterlar", "Bulochkalar"],
                                        "Yarim tayyor maxsulotlar": ["Chuchvara", "Somsa xamir", "Somsa",
                                                                     "Pitsa xamiri",
                                                                     "Lagmon", "Kotlet", "Lavash xamir"]},
          "Go'zallik": {"Makiyaj": ["Ko'zlar", "Lablar", "Makiyaj uchun aksessuarlar", "Qoshlar", "Yuz"],
                        "Yuz parvarishi": ["Muammoli terilar uchun maxsulotlar", "Namlash va oziklantirish", "Niqoblar",
                                           "Patichlar", "Skrab va piling", "Tozalash va yuvish"],
                        "Soch parvarishi": ["Aksesuarlar", "Buyash va kimyoviy jingalak kilish",
                                            "Sartarosh uchun professional asboblar",
                                            "Tozalash va parvarish uchun vositalar",
                                            "Turmaklash uchun vositalar"],
                        "Tana parvarishi": ["Aksesuarlar", "Dush va vanna uchun vositalar", "Namlash va oziqlantirish",
                                            "Quyoshda toblanish va quyoshdan ximoyalash"],
                        "Manikyur va pedyikyur": ["Gel-laklar", "Laklar",
                                                  "Praymerlar va yog'larni yo'qotuvchi maxsulotlar",
                                                  "Tirnok bo'yogini tozalovchi vositalar",
                                                  "Tirnok yopishtirish uchun materyallar"],
                        "To'plam": ["Sochlar uchun kosmetika to'plamlari",
                                    "Tana parvarishi uchun kosmetika  to'plamlari",
                                    "Yuz uchun to'plamlar"],
                        "Erkaklar uchun": ["Soch uchun", "Soqol va muylovlar uchun", "Yuz tana parvarishi"],
                        "Parfyumeriya": ["Aromat yog'lar", "Atirlar", "Odekolonlar", "Parfyumlangan suv",
                                         "Qurik atirlar",
                                         "Selektiv parfyumeriya", "Xushbuylangan suv"]},
          "Maishy kimyoviy moddalar": {
              "Xavoni musaffolashtirgichlar": ["Xavo tozalovchilar", "Xidlarni neytralash vositalari",
                                               "Xushbo'ylashtirgichlar"],
              "Idish yuvish vositalari": ["Kapsulalar va chayish vositalari", "Tabletkalar"],
              "Intim gigiyena": ["Dezodarantlar va antiperspirantlar", "Intim gigiyenasi uchun vositalar",
                                 "Prokladkalar va tanponlar"],
              "Og'iz bo'shligi gigiyenasi": ["Tish cho'tkalar", "Tish pastalar va gellar",
                                           "Tish okartiruvchi vositalar"],
              "Poyabzallarni parvarish kilish vositalari": ["Dezodarantlar", "Kremlar va vosklar",
                                                            "Poyabzal uchun buyoqlar",
                                                            "Poyabzal uchun chutkalar va gupkalar"],
              "Qogoz va paxta maxsulotlari": ["Nam salfetkalar", "Paxta yostiqchalari", "Paxta tayoqchalari",
                                              "Qogoz sochiklar va salfetkalar", "Xojatxona qogozi"],
              "Soqol olish uchun tovarlar": ["Britvalar, uskunalar", "Gellar va kupiklar",
                                             "Sokkol olish uchun tuplamlar va aksuarlar",
                                             "Sokol olishdan oldingi va keyingi surtiladigan vositalar"],
              "Sovun va xujalik sovuni": ["Beldilar", "Kosmetik sovun", "Xujalik sovunlari",
                                          "Skrab, suvenir, suyuk, yuvunish sovunlari"],
              "Maishiy texnika parvarishi uchun vositalar": ["Idish yuvish mashinalari uchun",
                                                             "Kir yuvish mashinalari uchun",
                                                             "Choynaklar uchun",
                                                             "Suvni yumshatish vositalari"],
              "Yuvish uchun vositalar": [
                  "Idish yuvish vositalari", "Mebel va polni parvarishlash uchun vositalar",
                  "Universal tozalash vositasi", "Vanna va xojatxona uchun vositalar",
              ],
              "Tozalash va yuvish vositalari": [
                  "Gel va suyukliklar", "Kapsulalar va tabletkalar", "Kir yuvish kukuni",
                  "Konditsionerlar va chayish vositalari", "Okartirgichlar va dog ketkazgichlar"]
          },
          "Hayvonlar uchun maxsulotlar": {
              "Gigiena": ["Gigiyena vositalari", "Xayvonlar uchun kosmetika", "Xayvonlarni parvarish kilish vositalari",
                          "Plyonkalar va tagliklar", "Spreylar va xidni yuk kilish vositalari"],
              "Itlar uchun": ["Itlar uchun buyinbog", "Itlar uchun xojatxonalar", "Itlar uchun kiyim va poyabzal",
                              "Ovqat beradigan idishlar", "Ozuqa va shirinliklar", "Uyinchoklar"],
              "Mushuklar uchun": ["Mushuklar uchun xojatxonalar", "Mushuklar uchun kiyim va tushaklar",
                                  "Ovqat beradigan idishlar", "Ozuqa va shirinliklar", "Uyinchoqlar"]}}
